[package]
name = "molecular-dynamics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.1"
rand = "0.8.5"
rand_distr = "0.4.3"
csv = "1.1.6"